### ISSUE TITLE
Initial release of Security API

### ISSUE THREAD

**Issue by muka** [muka/raptor#14]
- [x] Integrate security API with current Raptor API #13 
- [x] Support JWT #10 
- [x] Add user management API #9
- [x] Disconnect on permission change #7
