### ISSUE TITLE
Group features

### ISSUE THREAD

**Issue by muka** [muka/raptor#2]
Group
- [x] Management HTTP API #5  
- [x] Handle groups in dispatcher #6
- [x] Match hierarchy between objects/ACL #22
